name: U3D tests

on:
  workflow_dispatch

jobs:
  u3d_testing:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest', 'ubuntu-latest']
        u3d_version: [1.2.3, 1.3.2]
        ruby_version: [2.6.10, 3.1.2]
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby_version}}
      - name: Set the Env
        shell: bash
        run: |
          echo "U3D_SKIP_UPDATE_CHECK=1" >> $GITHUB_ENV
      - name: Install Unity installer (U3D)
        shell: bash
        run: gem install u3d -v ${{matrix.u3d_version}}
      - name: U3D help
        shell: bash
        run: |
          u3d --help
      - name: List Unity Versions
        shell: bash
        run: |
          u3d available --trace
      - name: List Unity Versions
        shell: bash
        run: |
          u3d available -p --trace